//======================GENERATED BY LLM======================






/* main.c —— 用协程实现的生成器
 *
 * 语义类似 Python 生成器：
 *   - 协程内部 coro_suspend 之前设置 yield_val，相当于 yield 一个值出去；
 *   - 主程序 gen_next 恢复协程时把 send_val 塞回去，相当于 send 一个值进去。
 *
 * 数据通道：ctx->params_nullable.coro_params 指向 gen_t。
 */

#include "coro.h"
#include <stdio.h>

/* 主程序 <-> 生成器 之间的通信块 */
typedef struct gen_t {
    int yield_val;   /* 协程 -> 主程序：本次 yield 出来的值 */
    int send_val;    /* 主程序 -> 协程：下一次 resume 时传入的值 */
    int done;        /* 生成器是否已结束 */
} gen_t;

/* ================= 生成器本体 ================= */
/* 依次产出 0, 10, 20, 30, 40，并在每次被唤醒时打印收到的 send_val */
static void counter_gen(struct coro_context_t* ctx) {
    gen_t* g = (gen_t*)ctx->params_nullable.coro_params;

    for (int i = 0; i < 5; ++i) {
        g->yield_val = i * 10;
        coro_suspend(ctx);                      /* yield：把控制权交回主程序 */
        printf("[coro]  被唤醒，收到 send_val = %d\n", g->send_val);
    }

    g->done = 1;
    coro_return(ctx);                           /* 结束协程 */
}

/* ================= 生成器对外接口 ================= */
/* 推进一次生成器：
 *   - 首次调用自动 startup
 *   - 之后调用会 resume，并把 send_val 送进去
 * 返回 1 表示本次产出了一个值（可以从 g->yield_val 取），返回 0 表示已结束。
 */
static int gen_next(struct coro_context_t* ctx, gen_t* g, int send_val) {
    switch (ctx->state) {
        case CORO_END:
            return 0;

        case CORO_INIT:
            if (!coro_startup(ctx)) return 0;
            break;

        case CORO_SUSPEND:
            g->send_val = send_val;
            coro_resume(ctx);
            break;

        default:
            return 0;
    }
    return ctx->state == CORO_SUSPEND;
}

/* ================= 主程序 ================= */
int main(void) {
    struct coro_context_t* ctx = coro_create(counter_gen);
    if (!ctx) {
        fprintf(stderr, "coro_create failed\n");
        return 1;
    }

    gen_t g = {0, 0, 0};
    ctx->params_nullable.coro_params = &g;

    int round = 0;
    while (gen_next(ctx, &g, round * 100)) {
        printf("[main]  第 %d 次 yield: %d\n", round, g.yield_val);
        ++round;
    }

    printf("[main]  生成器结束 (done=%d, yield 次数=%d)\n", g.done, round);

    coro_destory(ctx);
    return 0;
}
